import { defineConfig } from 'oxlint';

export default defineConfig({
  plugins: [
    // multiline
    'eslint',
    'import',
    'jsdoc',
    'node',
    'oxc',
    'promise',
    'typescript',
    'unicorn',
    'vitest',
  ],
  categories: {
    correctness: 'error',
    perf: 'error',
  },
  options: {
    typeAware: true,
    // handled by tsc
    typeCheck: false,
  },
  env: {
    builtin: true,
    es2026: true,
    browser: true,
    node: true,
    serviceworker: true,
  },
  ignorePatterns: [
    // multiline
    '.next/**/*',
    '**/next-env.d.ts',
    'container/**/*',
    'dist/**/*',
    'src/**/*.js',
    'package-lock.json',

    'mongoshrc.js',

    '!.storybook',
    '!**/.storybook',

    'config/pi/checks/**/*',
    'plans/**',
    'research/**',
  ],
  rules: {
    'constructor-super': 'error',
    'for-direction': 'error',
    'getter-return': 'error',
    'no-async-promise-executor': 'error',
    'no-case-declarations': 'error',
    'no-class-assign': 'error',
    'no-compare-neg-zero': 'error',
    'no-cond-assign': 'error',
    'no-const-assign': 'error',
    'no-constant-binary-expression': 'error',
    'no-constant-condition': 'error',
    'no-control-regex': 'error',
    'no-debugger': 'error',
    'no-delete-var': 'error',
    'no-dupe-class-members': 'off',
    'no-dupe-else-if': 'error',
    'no-dupe-keys': 'error',
    'no-duplicate-case': 'error',
    'no-empty': [
      'error',
      {
        allowEmptyCatch: true,
      },
    ],
    'no-empty-character-class': 'error',
    'no-empty-pattern': 'error',
    'no-empty-static-block': 'error',
    'no-ex-assign': 'error',
    'no-extra-boolean-cast': 'error',
    'no-fallthrough': 'error',
    'no-func-assign': 'error',
    'no-global-assign': 'error',
    'no-import-assign': 'error',
    'no-invalid-regexp': 'error',
    'no-irregular-whitespace': 'error',
    'no-loss-of-precision': 'error',
    'no-misleading-character-class': 'error',
    'no-new-native-nonconstructor': 'error',
    'no-nonoctal-decimal-escape': 'error',
    'no-obj-calls': 'error',
    'no-prototype-builtins': 'error',
    'no-redeclare': 'error',
    'no-regex-spaces': 'error',
    'no-self-assign': 'error',
    'no-setter-return': 'error',
    'no-shadow-restricted-names': 'error',
    'no-sparse-arrays': 'error',
    'no-this-before-super': 'error',
    'no-undef': 'error',
    'no-unreachable': 'error',
    'no-unsafe-finally': 'error',
    'no-unsafe-negation': 'error',
    'no-unsafe-optional-chaining': 'error',
    'no-unused-labels': 'error',
    'no-unused-private-class-members': 'error',
    'no-unused-vars': [
      'error',
      {
        argsIgnorePattern: '^_',
        caughtErrorsIgnorePattern: '^_',
        destructuredArrayIgnorePattern: '^_',
      },
    ],
    'no-useless-backreference': 'error',
    'no-useless-catch': 'error',
    'no-useless-escape': 'error',
    'no-with': 'error',
    'require-yield': 'error',
    'use-isnan': 'error',
    'valid-typeof': 'error',
    eqeqeq: ['error', 'smart'],
    'no-console': 'off',
    'no-implicit-coercion': [
      'error',
      {
        string: true,
        boolean: false,
        number: false,
      },
    ],
    'no-multi-str': 'error',
    'no-use-before-define': 'error',
    'object-shorthand': ['error', 'always'],
    'typescript/dot-notation': 'error',
    'no-array-constructor': 'error',
    'no-unused-expressions': 'error',
    'no-throw-literal': 'off',
    'prefer-promise-reject-errors': 'off',
    'require-await': 'off',
    'typescript/await-thenable': 'error',
    'typescript/ban-ts-comment': 'error',
    'typescript/no-array-delete': 'error',
    'typescript/no-base-to-string': 'error',
    'typescript/no-duplicate-enum-values': 'error',
    'typescript/no-duplicate-type-constituents': 'error',
    'typescript/no-empty-object-type': 'error',
    'typescript/no-explicit-any': 'off',
    'typescript/no-extra-non-null-assertion': 'error',
    'typescript/no-floating-promises': 'error',
    'typescript/no-for-in-array': 'error',
    'typescript/no-implied-eval': 'error',
    'typescript/no-misused-new': 'error',
    'typescript/no-misused-promises': [
      'error',
      {
        checksVoidReturn: false,
      },
    ],
    'typescript/no-namespace': 'error',
    'typescript/no-non-null-asserted-optional-chain': 'error',
    'typescript/no-redundant-type-constituents': 'error',
    'typescript/no-require-imports': 'error',
    'typescript/no-this-alias': 'error',
    'typescript/no-unnecessary-type-assertion': 'error',
    'typescript/no-unnecessary-type-constraint': 'error',
    'typescript/no-unsafe-argument': 'error',
    'typescript/no-unsafe-assignment': 'error',
    'typescript/no-unsafe-call': 'error',
    'typescript/no-unsafe-declaration-merging': 'error',
    'typescript/no-unsafe-enum-comparison': 'error',
    'typescript/no-unsafe-function-type': 'error',
    'typescript/no-unsafe-member-access': 'error',
    'typescript/no-unsafe-return': 'error',
    'typescript/no-unsafe-unary-minus': 'error',
    'typescript/no-wrapper-object-types': 'error',
    'typescript/only-throw-error': 'error',
    'typescript/prefer-as-const': 'error',
    'typescript/prefer-namespace-keyword': 'error',
    'typescript/prefer-promise-reject-errors': 'error',
    'typescript/require-await': 'error',
    'typescript/restrict-plus-operands': 'error',
    'typescript/restrict-template-expressions': 'error',
    'typescript/triple-slash-reference': 'error',
    'typescript/unbound-method': 'error',
    'no-empty-function': 'error',
    'typescript/adjacent-overload-signatures': 'error',
    'typescript/array-type': 'error',
    'typescript/ban-tslint-comment': 'error',
    'typescript/class-literal-property-style': 'error',
    'typescript/consistent-generic-constructors': 'error',
    'typescript/consistent-indexed-object-style': 'error',
    'typescript/consistent-type-assertions': 'error',
    'typescript/consistent-type-definitions': 'error',
    'typescript/no-confusing-non-null-assertion': 'error',
    'typescript/no-inferrable-types': 'error',
    'typescript/non-nullable-type-assertion-style': 'error',
    'typescript/prefer-find': 'error',
    'typescript/prefer-for-of': 'error',
    'typescript/prefer-function-type': 'error',
    'typescript/prefer-includes': 'error',
    'typescript/prefer-nullish-coalescing': 'error',
    'typescript/prefer-optional-chain': 'error',
    'typescript/prefer-regexp-exec': 'error',
    'typescript/prefer-string-starts-ends-with': 'error',
    'typescript/consistent-type-imports': 'error',
    'typescript/consistent-type-exports': 'error',
    'typescript/explicit-function-return-type': [
      'error',
      {
        allowExpressions: true,
      },
    ],
    'typescript/no-empty-interface': 'off',
    'typescript/no-non-null-assertion': 'off',
    // Forces `vi.fn<() => Foo>()` on every mock; not previously enforced.
    'vitest/require-mock-type-parameters': 'off',
  },
  overrides: [
    {
      files: ['**/*.json', '**/*.jsonc', '**/*.json5'],
      rules: {
        '@eslint/json/no-duplicate-keys': 'error',
        '@eslint/json/no-empty-keys': 'error',
        '@eslint/json/no-unnormalized-keys': 'error',
        '@eslint/json/no-unsafe-values': 'error',
      },
      jsPlugins: ['@eslint/json'],
    },
    {
      files: [
        'config/pi/extensions/**/*.{ts,mts,cts,js,mjs,cjs}',
        'lib/node/pi/ext/**/*.{ts,mts,cts,js,mjs,cjs}',
        'tests/lib/node/pi/ext/**/*.{ts,mts,cts,js,mjs,cjs}',
      ],
      rules: {
        // 'typescript/await-thenable': 'off',
        // 'typescript/consistent-return': 'off',
        // 'typescript/consistent-type-exports': 'off',
        // 'typescript/dot-notation': 'off',
        // 'typescript/no-array-delete': 'off',
        // 'typescript/no-base-to-string': 'off',
        // 'typescript/no-confusing-void-expression': 'off',
        // 'typescript/no-deprecated': 'off',
        // 'typescript/no-duplicate-type-constituents': 'off',
        // 'typescript/no-floating-promises': 'off',
        // 'typescript/no-for-in-array': 'off',
        // 'typescript/no-implied-eval': 'off',
        // 'typescript/no-meaningless-void-operator': 'off',
        // 'typescript/no-misused-promises': 'off',
        // 'typescript/no-misused-spread': 'off',
        // 'typescript/no-mixed-enums': 'off',
        // 'typescript/no-redundant-type-constituents': 'off',
        // 'typescript/no-unnecessary-boolean-literal-compare': 'off',
        // 'typescript/no-unnecessary-condition': 'off',
        // 'typescript/no-unnecessary-qualifier': 'off',
        // 'typescript/no-unnecessary-template-expression': 'off',
        // 'typescript/no-unnecessary-type-arguments': 'off',
        // 'typescript/no-unnecessary-type-assertion': 'off',
        // 'typescript/no-unnecessary-type-conversion': 'off',
        // 'typescript/no-unnecessary-type-parameters': 'off',
        // 'typescript/no-unsafe-argument': 'off',
        // 'typescript/no-unsafe-assignment': 'off',
        // 'typescript/no-unsafe-call': 'off',
        // 'typescript/no-unsafe-enum-comparison': 'off',
        // 'typescript/no-unsafe-member-access': 'off',
        // 'typescript/no-unsafe-return': 'off',
        // 'typescript/no-unsafe-type-assertion': 'off',
        // 'typescript/no-unsafe-unary-minus': 'off',
        // 'typescript/no-useless-default-assignment': 'off',
        // 'typescript/non-nullable-type-assertion-style': 'off',
        // 'typescript/only-throw-error': 'off',
        // 'typescript/prefer-find': 'off',
        // 'typescript/prefer-includes': 'off',
        // 'typescript/prefer-nullish-coalescing': 'off',
        // 'typescript/prefer-optional-chain': 'off',
        // 'typescript/prefer-promise-reject-errors': 'off',
        // 'typescript/prefer-readonly': 'off',
        // 'typescript/prefer-readonly-parameter-types': 'off',
        // 'typescript/prefer-reduce-type-parameter': 'off',
        // 'typescript/prefer-regexp-exec': 'off',
        // 'typescript/prefer-return-this-type': 'off',
        // 'typescript/prefer-string-starts-ends-with': 'off',
        // 'typescript/promise-function-async': 'off',
        // 'typescript/related-getter-setter-pairs': 'off',
        // 'typescript/require-array-sort-compare': 'off',
        'typescript/require-await': 'off',
        // 'typescript/restrict-plus-operands': 'off',
        // 'typescript/restrict-template-expressions': 'off',
        // 'typescript/return-await': 'off',
        // 'typescript/strict-boolean-expressions': 'off',
        // 'typescript/strict-void-return': 'off',
        // 'typescript/switch-exhaustiveness-check': 'off',
        // 'typescript/unbound-method': 'off',
        // 'typescript/use-unknown-in-catch-callback-variable': 'off',
      },
    },
  ],
});
