#!/bin/bash

# if there are any baked in arguments they are defined here
args=(  )
IS_REMAIN_ARGS=0

for arg in "$@"
do
  # if argument is a file, then expand it to windows paths
  if [[ ${IS_REMAIN_ARGS} == 1 ]] || [[ "$arg" != -* && -e "$(wslpath -u "$arg" 2>/dev/null)" ]]; then
    # echo "arg $arg is a file"
    args=("${args[@]}" "$(wslpath -u "$arg")")
  else
    # echo "arg $arg is not a file"
    args=("${args[@]}" "$arg")
  fi
  if [[ "$arg" == "--" ]]; then
    IS_REMAIN_ARGS=1
  fi
done

# echo "${args[@]}" >> /tmp/wslgit-runlog

# vscode uses the output of this command to determine if the repo is a git repo, but vscode also expects a windows
# path as the response
if [[ "${args[0]}" == "rev-parse" ]]; then
  wslpath -w "$(git "${args[@]}")"
else
  exec git "${args[@]}"
fi
