
[branch "master"]
  merge = refs/heads/master
  remote = origin

[branch "main"]
  merge = refs/heads/main
  remote = origin

[remote "origin"]
  # automatically fetch and override tags
  fetch = +refs/tags/*:refs/tags/*

[remote "upstream"]
  # automatically fetch and override tags
  fetch = +refs/tags/*:refs/tags/*
