[remote "origin"]
  # Force retagged remote tags during fetch/pull when on a branch.
  fetch = +refs/tags/*:refs/tags/*

[remote "upstream"]
  # Force retagged remote tags during fetch/pull when on a branch.
  fetch = +refs/tags/*:refs/tags/*
